language: node_js

node_js:
  - "5.0"
  - "4.1"

before_install:
  - mkdir dist

after_script:
  - npm run coverage
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
